# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        description: Simply check whether files parse as valid python.
      - id: trailing-whitespace
        description: Trims trailing whitespace
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline.
      - id: check-added-large-files
        description: Prevent giant files from being committed.
      - id: check-case-conflict
        description: Check for files with names that would conflict on case-insensitive filesystems like MacOS/Windows.
      - id: no-commit-to-branch
        description: Protect specific branches from direct checkins.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python -m unittest discover -s tests
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
        stages: [ commit ]
