[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py311"

[[tool.mypy.overrides]]
module = [
    "tqdm.*",
    "ahocorasick.*",
]
ignore_missing_imports = true
